### ISSUE TITLE
having an issue with this

### ISSUE THREAD

**Issue by Fido-Actual** [Randolio/randol_moneywash#2]
[script:randol_moneyw] SCRIPT ERROR: @randol_moneywash/server/sv_moneywash.lua:22: attempt to perform arithmetic on a nil value (field 'worth')

**Comment by Fido-Actual** [comment]
there isn't an issue with this script, but with another script not assigning a value to the markedbills when given.  i have resolved the issue.

**Comment by FETEWALKER** [comment]
Can You Teach Me How You Solved This Problem?
